# Generated by Django 3.1.5 on 2021-01-13 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da Instituição')),
                ('atoDeInscricao', models.CharField(max_length=100, verbose_name='Ato de Inscrição')),
                ('codigoINEP', models.CharField(max_length=10, verbose_name='Código INEP')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('municipio', models.CharField(max_length=20, verbose_name='Municipio')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('modalidades', models.CharField(max_length=20, verbose_name='Modalidades')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Nome de Usuario')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do Aluno')),
                ('dtNascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('rg', models.CharField(max_length=10, verbose_name='RG/RNE/RA')),
                ('nomeMae', models.CharField(max_length=50, verbose_name='Nome da Mãe')),
                ('nomePai', models.CharField(max_length=50, verbose_name='Nome do Pai')),
                ('nivelEnsino', models.CharField(max_length=50, verbose_name='Nível de Ensino')),
                ('anoConclusao', models.DateField(verbose_name='Ano de Conclusão')),
                ('observacoes', models.TextField(verbose_name='Observações')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.instituicao')),
            ],
        ),
    ]
